name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restaurer les dépendances
        run: dotnet restore FD.TechTest.LibraryManagement.sln

      - name: Compiler
        run: >
          dotnet build FD.TechTest.LibraryManagement.sln
          --configuration Release
          --no-restore

      - name: Exécuter les tests
        run: >
          dotnet test
          src/Tests/FD.TechTest.LibraryMangement.Tests/FD.TechTest.LibraryMangement.ApplicationCore.Tests.csproj
          --configuration Release
          --no-build
          --verbosity normal